### ISSUE TITLE
listing-codesearch doesn't exist as a separate package

### ISSUE THREAD

**Issue by mdorman** [abingham/emacs-codesearch#10]
You declare that as a dependency in the header, but it doesn't exist as a separate package.  I think you just want to `require` it.

**Comment by abingham** [comment]
Do you mean in `projectile-codesearch.el`? I'll be happy to update that. Should I have it depend on `codesearch` instead, since that's the melpa recipe that brings in `listing-codesearch.el`? (I admit I'm a bit fuzzy on how all of these dependency declarations, repositories, etc. relate to one another.)

**Comment by mdorman** [comment]
Sorry, yes, I meant in `projectile-codesearch.el`.

I think your options are either:

1. split `listing-codesearch.el` into its own package
 * add a `listing-codesearch` recipe into melpa
 * remove `listing-codesearch.el` from the `codesearch` recipe
 * add `listing-codesearch` to the `package-requires` header of `codesearch.el`), or:
2. have `projectile-codesearch.el` depend on `codesearch`
 * change `listing-codesearch` to `codesearch` in its 'package-requires' header

Certainly one is simpler than the other.

**Comment by abingham** [comment]
Yeah, (2) is the way to go for now. I'll get that taken care of soon.

**Comment by abingham** [comment]
Should be fixed in 4e6a2382c26d1218a4a007d31de2bab8ef9d2e7c, but re-open this if I've screwed something up. Thanks!

**Comment by mdorman** [comment]
Looks OK to me.

**Comment by abingham** [comment]
Thanks!

**Comment by rogerwang** [comment]
The README of this repo needs updates as well.
