### ISSUE TITLE
Remove extracted files

### ISSUE THREAD

**Issue by DamienCassou** [abingham/emacs-codesearch#11]
You might want to remove files you have moved to their own repository. e.g., `counsel-codesearch`.

**Comment by abingham** [comment]
Haven't I already? The only files in the new repo are `counsel-codesearch.el` and a README. But I make dumb mistakes all the time, so let me know if I've missed something.

**Comment by DamienCassou** [comment]
It seems you did. Sorry for the noise :-).

**Comment by abingham** [comment]
No worries.
